amqphost = '172.100.0.13'
amqppassword = 'guest'
amqpport = '5672'
amqpprefix = 'amqp://'
amqpuser = 'guest'
basepnduuid = '5f20f34b-cbd0-4511-9ddc-c50cf6a3b49d'
basesouthboundtype = 1
basesouthbounduuid = 'ca29311a-3b17-4385-96f8-515b602a97ac'
cli_pnd = '0455b241-5863-4660-ad15-dfde7617738e'
cli_sbi = 'a249f2d2-f7da-481d-8a99-b7f11471e0af'
config = './configs/gosdn.toml'
csbi-orchestrator = 'clab-gosdn_csbi_arista_base-csbi-orchestrator:55056'
databaseconnection = 'mongodb://root:example@172.100.0.11:27017'
defaultjwtduration = 24
filesystempathtostores = 'stores'
gnmisubscriptionspath = 'configs/gNMISubscriptions.txt'
help = false
log-level = 'debug'
plugin-folder = 'plugins'
pnduuid = 'bf8160d4-4659-4a1b-98fd-f409a04111ec'
security = 'insecure'
socket = ':55055'
